server:
  port: 8081

spring:
  redis:
    host: crpyto-crunch-redis-001.mzagiz.0001.apn2.cache.amazonaws.com
    port: 6379

elasticsearch:
  host: search-crpyto-crunch-elasticsearch-y2o5bnrlo2pejnym25smqkflge.ap-northeast-2.es.amazonaws.com
  scheme: https
  port: 443
  username: admin
  password: ENC(T3/wtgHBcIDlSANgxB5KOh5ZEhP13J4nzkLSdcXpGIw=)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor